---
language: ruby
sudo: false
cache: bundler
rvm:
- 2.6.4
script: bundle exec rake $TASK
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
env:
- TASK='jekyll:check'
- TASK='jekyll:check_external_links'
